# https://github.com/ndmitchell/hlint
- arguments:
    - -XNamedFieldPuns
    - -XTemplateHaskell
- extensions:
  - default: false
- flags:
  - default: false
- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
- ignore: { name: Use <|> }
- ignore: { name: Use lambda-case }
