name: rattletrap
version: 6.2.3

category: Game
description: Rattletrap parses and generates Rocket League replays.
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/rattletrap
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Parse and generate Rocket League replays.

dependencies:
  aeson-pretty: '>= 0.8.5 && < 0.9'
  aeson: '>= 1.2.4 && < 1.5'
  base: '>= 4.11.1 && < 4.13'
  binary-bits: '>= 0.5 && < 0.6'
  binary: '>= 0.8.5 && < 0.9'
  bytestring: '>= 0.10.8 && < 0.11'
  containers: '>= 0.5.10 && < 0.7'
  filepath: '>= 1.4.1 && < 1.5'
  http-client-tls: '>= 0.3.5 && < 0.4'
  http-client: '>= 0.5.10 && < 0.7'
  template-haskell: '>= 2.13.0 && < 2.15'
  text: '>= 1.2.3 && < 1.3'
  transformers: '>= 0.5.2 && < 0.6'
ghc-options:
  - -optP -Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missing-exported-signatures # https://ghc.haskell.org/trac/ghc/ticket/14794
  - -Wno-missing-import-lists
  - -Wno-safe
  - -Wno-unsafe

flags:
  static:
    default: false
    manual: true

library:
  source-dirs: library

executable:
  dependencies: rattletrap
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
  source-dirs: executables
  when:
    - condition: flag(static)
      ld-options: -static

tests:
  test:
    dependencies:
      clock: '>= 0.7.2 && < 0.8'
      HUnit: '>= 1.6.0 && < 1.7'
      rattletrap: -any
      temporary: '>= 1.2.1 && < 1.4'
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    source-dirs: tests
