services:
  devcontainer:
    command: sh -c 'while sleep 1; do :; done'
    image: ghcr.io/acilearning/docker-haskell:9.4.2
    init: true
    volumes:
      - ..:/workspaces/rattletrap
    working_dir: /workspaces/rattletrap
volumes:
  cabal: null
  cabal-store:
    external: true
