services:
  devcontainer:
    command: sh -c 'while sleep 1; do :; done'
    image: public.ecr.aws/acilearning/haskell:9.4.3
    init: true
    volumes:
      - ..:/workspaces/rattletrap
    working_dir: /workspaces/rattletrap
volumes:
  cabal: null
  cabal-store:
    external: true
