name: ci
on:
  push: null
  release:
    types:
      - created
jobs:

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tfausak/hlint-action@v1
        with:
          config: config/hlint.yaml

  brittany:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tfausak/brittany-action@v1
        with:
          config: config/brittany.yaml

  build:
    strategy:
      matrix:
        include:
          - platform: ubuntu
            ghc: 9.4.2
          - platform: ubuntu
            ghc: 9.2.2
          - platform: macos
            ghc: 9.2.2
          - platform: windows
            ghc: 9.2.2
    name: GHC ${{ matrix.ghc }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}-latest
    steps:

      - uses: actions/checkout@v2

      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - run: cabal configure --enable-tests --flags pedantic --jobs --test-show-details direct

      - run: cabal freeze && cat cabal.project.freeze

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.platform }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.platform }}-${{ matrix.ghc }}-

      - run: cabal build

      - run: cabal test --test-options '+RTS -s -RTS'

      - run: npm install ajv-cli

      - run: cabal exec runghc src/util/check-schema.hs

      - run: cabal check

      - run: mkdir artifact

      - run: mkdir artifact/${{ matrix.platform }}

      - run: mkdir artifact/${{ matrix.platform }}/${{ matrix.ghc }}

      - run: cabal sdist --output-dir artifact/${{ matrix.platform }}/${{ matrix.ghc }}

      - run: cabal exec runghc src/util/copy-executable.hs artifact/${{ matrix.platform }}/${{ matrix.ghc }}

      - uses: svenstaro/upx-action@v2
        with:
          file: artifact/${{ matrix.platform }}/${{ matrix.ghc }}/rattletrap

      - run: cp output/schema.json artifact/${{ matrix.platform }}/${{ matrix.ghc }}

      - uses: actions/upload-artifact@v2
        with:
          path: artifact

  release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/octet-stream
          asset_name: rattletrap-${{ github.event.release.tag_name }}-ubuntu
          asset_path: artifact/ubuntu/9.2.2/rattletrap
          upload_url: ${{ github.event.release.upload_url }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/octet-stream
          asset_name: rattletrap-${{ github.event.release.tag_name }}-macos
          asset_path: artifact/macos/9.2.2/rattletrap
          upload_url: ${{ github.event.release.upload_url }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/octet-stream
          asset_name: rattletrap-${{ github.event.release.tag_name }}-windows.exe
          asset_path: artifact/windows/9.2.2/rattletrap
          upload_url: ${{ github.event.release.upload_url }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/gzip
          asset_name: rattletrap-${{ github.event.release.tag_name }}.tar.gz
          asset_path: artifact/ubuntu/9.2.2/rattletrap-${{ github.event.release.tag_name }}.tar.gz
          upload_url: ${{ github.event.release.upload_url }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/json
          asset_name: rattletrap-${{ github.event.release.tag_name }}-schema.json
          asset_path: artifact/ubuntu/9.2.2/schema.json
          upload_url: ${{ github.event.release.upload_url }}

      - run: cabal upload --publish --username '${{ secrets.HACKAGE_USERNAME }}' --password '${{ secrets.HACKAGE_PASSWORD }}' artifact/ubuntu/9.2.2/rattletrap-${{ github.event.release.tag_name }}.tar.gz

      - run: mv artifact/ubuntu/9.2.2/rattletrap docker/rattletrap

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile
          tags: taylorfausak/rattletrap:${{ github.event.release.tag_name }}
          push: true
