name: release
on:
  release:
    types:
      - created
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: rattletrap-executable-${{ github.sha }}-ubuntu-20.04
          path: docker/rattletrap
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile
          tags: taylorfausak/rattletrap:version-${{ github.event.release.tag_name }}
          push: true
